-- MySQL Script generated by MySQL Workbench
-- Thu May 11 19:39:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema data
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `data` DEFAULT CHARACTER SET utf8mb4 ;
USE `data` ;

-- -----------------------------------------------------
-- Table `data`.`userType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data`.`userType` (
  `typeId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`typeId`),
  UNIQUE INDEX `typeId_UNIQUE` (`typeId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data`.`sales` (
  `saleId` INT NOT NULL AUTO_INCREMENT,
  `total` DECIMAL NOT NULL,
  `createDate` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`saleId`),
  UNIQUE INDEX `salesId_UNIQUE` (`saleId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `image` VARCHAR(255) NULL,
  `typeId` INT NOT NULL,
  `saleId` INT NOT NULL,
  PRIMARY KEY (`id`, `email`, `typeId`, `saleId`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_users_userType1_idx` (`typeId` ASC) VISIBLE,
  INDEX `fk_users_sales1_idx` (`saleId` ASC) VISIBLE,
  CONSTRAINT `fk_users_userType1`
    FOREIGN KEY (`typeId`)
    REFERENCES `data`.`userType` (`typeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_sales1`
    FOREIGN KEY (`saleId`)
    REFERENCES `data`.`sales` (`saleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data`.`categories` (
  `categoryId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `parentId` INT NULL,
  PRIMARY KEY (`categoryId`),
  UNIQUE INDEX `categoryId_UNIQUE` (`categoryId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data`.`product` (
  `productId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `price` DECIMAL NOT NULL,
  `categoryId` INT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`productId`, `categoryId`),
  UNIQUE INDEX `idproduct_UNIQUE` (`productId` ASC) VISIBLE,
  INDEX `fk_product_categories_idx` (`categoryId` ASC) VISIBLE,
  CONSTRAINT `fk_product_categories`
    FOREIGN KEY (`categoryId`)
    REFERENCES `data`.`categories` (`categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `data`.`soldProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data`.`soldProduct` (
  `soldProductId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL NOT NULL,
  `quantity` INT NOT NULL,
  `categoryId` INT NOT NULL,
  `saleId` INT NOT NULL,
  PRIMARY KEY (`soldProductId`, `categoryId`, `saleId`),
  UNIQUE INDEX `soldProductId_UNIQUE` (`soldProductId` ASC) VISIBLE,
  INDEX `fk_soldProduct_categories1_idx` (`categoryId` ASC) VISIBLE,
  INDEX `fk_soldProduct_sales1_idx` (`saleId` ASC) VISIBLE,
  CONSTRAINT `fk_soldProduct_categories1`
    FOREIGN KEY (`categoryId`)
    REFERENCES `data`.`categories` (`categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_soldProduct_sales1`
    FOREIGN KEY (`saleId`)
    REFERENCES `data`.`sales` (`saleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
